site_name: Sadples.cc Docs

nav:
  - Home: index.md
  - How the fuck do I:
    - Fix:
      - Alarms: how/fix/alarms.md
    - Remove:
      - Fake Microsoft Scam: how/remove/fakemicrosoft.md
    - Setup:
      - Windows without Microsoft Account: how/setup/windows.md
theme:
  name: readthedocs
extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - admonition
  - pymdownx.details # Required if you want collapsible admonitions
  - pymdownx.superfences # Required to nest complex code blocks inside admonitions

